### PR TITLE
Make QuarkusAiServices override upstream maxSequentialToolsInvocations method

### LINKED ISSUE #2373: RuntimeException: Something is wrong, exceeded 10 sequential tool executions
## Issue

I got this issue even if `maxSequentialToolsInvocations` is set to `100`. Why ?

```
I see the tool results are being returned as the resource listing. Let me explicitly read the automated_responses.yml file and the templates.", thinking = null, toolExecutionRequests = [ToolExecutionRequest { id = "toolu_vrtx_01QFBjnXgbEGy91UuQH12Jd3", name = "readFile", arguments = "{"path":".claude/automated_responses.yml"}" }, ToolExecutionRequest { id = "toolu_vrtx_01XktB4ZDTUZjkyJsmGcbRuB", name = "globFiles", arguments = "{"path":"src/main/resources","pattern":"**/*"}" }], attributes = {} }, metadata = ChatResponseMetadata{id='null', modelName='null', tokenUsage=null, finishReason=null} }                                   
java.lang.RuntimeException: Something is wrong, exceeded 10 sequential tool executions                                                                                                                              
        at dev.langchain4j.internal.Exceptions.runtime(Exceptions.java:38)
        at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.doImplement0(AiServiceMethodImplementationSupport.java:427)
        at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.doImplement(AiServiceMethodImplementationSupport.java:207)
        at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.implement(AiServiceMethodImplementationSupport.java:182)
        at MigrationAssistant$$QuarkusImpl.chat(Unknown Source)
        at SkillsAgent.run(SkillsAgent.java:62)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
```

Here is jbang script used on a Spring Boot TODO application to be migrated using this skill: https://github.com/quarkusio/quarkus-skills/pull/4

```
///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS io.quarkus:quarkus-picocli:3.31.3
//DEPS dev.langchain4j:langchain4j:1.13.0
//DEPS dev.langchain4j:langchain4j-skills:1.13.0-beta23
//DEPS dev.snowdrop.mtool.ai:vertex-ai-anthropic:1.0.5-SNAPSHOT
//SOURCES MigrationAssistant.java
//SOURCES ScannerTool.java

import dev.langchain4j.memory.chat.MessageWindowChatMemory;
import dev.langchain4j.model.chat.ChatModel;
import dev.langchain4j.service.AiServices;
import dev.langchain4j.skills.FileSystemSkillLoader;
import dev.langchain4j.skills.Skills;
import io.quarkiverse.langchain4j.vertexai.runtime.anthropic.VertexAiAnthropicChatModel;
import picocli.CommandLine;

import java.nio.file.Path;
import java.time.Duration;

@CommandLine.Command
public class SkillsAgent implements Runnable {

    @CommandLine.Option(
            names = {"-s", "--skill"},
            description = "Path directory of the skill to be executed",
            required = true
    )
    String skillsPath;

    @Override
    public void run() {
        String projectId = getEnv("QUARKUS_LANGCHAIN4J_VERTEXAI_ANTHROPIC_PROJECT_ID", "dummy");
        String location = getEnv("QUARKUS_LANGCHAIN4J_VERTEXAI_ANTHROPIC_LOCATION", "dummy");
        String modelId = getEnv("QUARKUS_LANGCHAIN4J_VERTEXAI_ANTHROPIC_MODEL_ID", "claude-opus-4-6");
        String publisher = getEnv("QUARKUS_LANGCHAIN4J_VERTEXAI_ANTHROPIC_PUBLISHER", "anthropic");
        int duration = Integer.parseInt(getEnv("QUARKUS_LANGCHAIN4J_VERTEXAI_ANTHROPIC_DURATION", "30"));
        int maxTokens = Integer.parseInt(getEnv("QUARKUS_LANGCHAIN4J_VERTEXAI_ANTHROPIC_MAX_TOKENS", "1000"));
        boolean logRequests = Boolean.parseBoolean(getEnv("QUARKUS_LANGCHAIN4J_VERTEXAI_ANTHROPIC_LOG_REQUESTS", "false"));
        boolean logResponses = Boolean.parseBoolean(getEnv("QUARKUS_LANGCHAIN4J_VERTEXAI_ANTHROPIC_LOG_RESPONSES", "false"));

        validateRequired(projectId, "QUARKUS_LANGCHAIN4J_VERTEXAI_ANTHROPIC_PROJECT_ID");
        validateRequired(location, "QUARKUS_LANGCHAIN4J_VERTEXAI_ANTHROPIC_LOCATION");

        ChatModel model = VertexAiAnthropicChatModel.builder()
                .projectId(projectId)
                .location(location)
                .modelId(modelId)
                .publisher(publisher)
                .maxOutputTokens(maxTokens)
                .timeout(Duration.ofSeconds(duration))
                .logRequests(logRequests)
                .logResponses(logResponses)
                .logCurl(false)
                .build();

        Skills skills = Skills.from(FileSystemSkillLoader.loadSkill(Path.of(skillsPath)));

        MigrationAssistant agent = AiServices.builder(MigrationAssistant.class)
                .chatModel(model)
                .chatMemory(MessageWindowChatMemory.withMaxMessages(20))
                .tools(new ScannerTool())
                .maxSequentialToolsInvocations(100)
                .systemMessage("You have access to the following skills:\n" + skills.formatAvailableSkills()
                        + "\nWhen the user's request relates to one of these skills, activate it first.")
                .build();

        System.out.println("=== Migration Agent Online ===");
        String response = agent.chat("Migrate Spring Boot applications to Quarkus. Use the automated_responses.yml to get answers");
        System.out.println("Agent: " + response);
    }

    /**
     * Helper to get Env Var or return a default.
     */
    private static String getEnv(String name, String defaultValue) {
        String val = System.getenv(name);
        return (val != null && !val.isBlank()) ? val : defaultValue;
    }

    /**
     * Helper to enforce required fields.
     */
    private static void validateRequired(String value, String envName) {
        if (value == null || value.isBlank() || value.equals("dummy")) {
            throw new IllegalStateException(
                    "CRITICAL ERROR: The environment variable '" + envName + "' is required but not set.");
        }
    }
}
```

### PR DESCRIPTION
**Pull request by omatheusmesmo**
The QuarkusAiServices builder defined `maxSequentialToolInvocations(Integer)` which does not override the upstream `AiServices#maxSequentialToolsInvocations(int)`. This caused the value set via the programmatic builder to be ignored at runtime, always falling back to the default of 10.

This PR adds the missing `@Override` and removes the old non-overriding method.

Note: the naming across the integration is inconsistent (annotation attribute, config property, internal field — all use different names for the same concept). This PR only fixes the immediate bug. A broader unification would be a breaking change and is better discussed separately.

- Fixes: #2373

### CODE REVIEW

File: core/runtime/src/main/java/io/quarkiverse/langchain4j/QuarkusAiServicesFactory.java [hunk 1]
```diff
@@ -70,8 +70,21 @@ public AiServices<T> imageModel(ImageModel imageModel) {
...
+         *             This builder method does not override the upstream
+         *             {@code AiServices#maxSequentialToolsInvocations(int)} method,
+         *             so the value set here is not applied when calling the upstream-named method,
+         *             which is the one users naturally call.
+         */
+        @Deprecated(since = "1.10.0", forRemoval = true)
         public AiServices<T> maxSequentialToolInvocations(Integer maxSequentialToolInvocations) {
-            quarkusAiServiceContext().maxSequentialToolExecutions = maxSequentialToolInvocations;
+            return maxSequentialToolsInvocations(maxSequentialToolInvocations);
+        }
```
Comment (geoand) [inline core/runtime/src/main/java/io/quarkiverse/langchain4j/QuarkusAiServicesFactory.java]: I don't see a reason to keep this around, as `QuarkusAsiServicesFactory` is not part of the exposed API

**Review by geoand — COMMENTED** [review]
Thanks! I added a comment

File: core/runtime/src/main/java/io/quarkiverse/langchain4j/QuarkusAiServicesFactory.java (hunk 1 above)
Comment (omatheusmesmo) [reply core/runtime/src/main/java/io/quarkiverse/langchain4j/QuarkusAiServicesFactory.java]: > I don't see a reason to keep this around, as `QuarkusAsiServicesFactory` is not part of the exposed API

Sorry. I incorrectly assumed QuarkusAiServices was part of the public API. I've removed.

**Comment by omatheusmesmo** [comment]
> Thanks! I added a comment

Hello @geoand , do you think it makes sense to open an issue to align the naming (annotation attribute, config property, internal field) in a future PR, perhaps with deprecations where needed? Or would that be an unnecessary breaking change?

**Comment by geoand** [comment]
Sure, we can do that. It would likely be a breaking change, but it makes sense

**Comment by omatheusmesmo** [comment]
@geoand , the 3 failed jobs all failed with the same JBang download error (exit code 22). Could you please re-run them? Looks like a GitHub issue.

**Review by geoand — APPROVED** [review]
Thanks!
