### PR TITLE
When using a ChatModel either directly or through an agent always include all tag keys with sentinel defaults

### LINKED ISSUE #2349: MetricsChatModelListener registers gen_ai.client.token.usage with inconsistent tag sets in agentic/manual ChatModel producer scenarios
## Summary

In a Quarkus application using `quarkus-langchain4j` with agentic interfaces (`@Agent`, `@SequenceAgent`, etc.), `MetricsChatModelListener` can register the same Micrometer metric name with different tag sets, which causes Prometheus to reject the second registration.

The metric involved is:

- `gen_ai.client.token.usage`

Prometheus error:

```text
java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys.
There is already an existing meter named 'gen_ai_client_token_usage_total' containing tag keys
[gen_ai_operation_name, gen_ai_request_model, gen_ai_response_model, gen_ai_token_type].
The meter you are attempting to register has keys
[ai_service_class_name, ai_service_method_name, gen_ai_operation_name, gen_ai_request_model, gen_ai_response_model, gen_ai_token_type].
```
## Environment

- Quarkus `3.34.x`
- quarkus-langchain4j BOM `1.7.x`
- OpenAI-compatible provider through Quarkus LangChain4j OpenAI
- Micrometer Prometheus registry enabled (`/q/metrics`)
- Agentic APIs (`@Agent`) instead of classic `@RegisterAiService`
- Manual `@Produces` `ChatModel` / `StreamingChatModel`

### PR DESCRIPTION
**Pull request by mariofusco**
The problem was that `MetricsChatModelListener` conditionally adds `ai_service.class_name` and `ai_service.method_name` tags to metrics based on whether a Vert.x duplicated context is active. This means that depending on this condition the same metric name could get registered with different tag key sets, while Prometheus requires all meters with the same name to have identical tag keys, and rejects the second registration with `IllegalArgumentException`.

The fix is simply to always include all tag keys with sensible defaults.

- Closes: #2349

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Review by saulocn — APPROVED** [review]

**Comment by geoand** [comment]
CI seems to not like the change :)

**Comment by mariofusco** [comment]
> CI seems to not like the change :)

I saw :) I will give a look.

**Comment by mariofusco** [comment]
@geoand it should be ok now

File: agentic/deployment/src/test/java/io/quarkiverse/langchain4j/agentic/deployment/AgentPrometheusTest.java [hunk 1]
```diff
@@ -0,0 +1,176 @@
...
+        Metrics.globalRegistry.add(prometheus);
+    }
+
+    @AfterAll
+    static void removePrometheusRegistry() {
+        if (prometheus != null) {
+            Metrics.globalRegistry.remove(prometheus);
+            prometheus.close();
+        }
+    }
```
Comment (geoand) [inline agentic/deployment/src/test/java/io/quarkiverse/langchain4j/agentic/deployment/AgentPrometheusTest.java]: Do we really need this? IIRC, we've never used this and usually just use the in-memory registry for tests

Comment (mariofusco) [reply agentic/deployment/src/test/java/io/quarkiverse/langchain4j/agentic/deployment/AgentPrometheusTest.java]: Not sure, that's used to check assertions against that `PrometheusMeterRegistry`. Is there a better way to do this? Should I remove that test completely?

Comment (geoand) [reply agentic/deployment/src/test/java/io/quarkiverse/langchain4j/agentic/deployment/AgentPrometheusTest.java]: We need the test, but my point is that we don't need the Prometheus registry just for the test. See https://github.com/quarkusio/quarkus/blob/6b2c1ef050bfed40e842447bb2b0c83d379f20b2/extensions/micrometer/deployment/src/test/java/io/quarkus/micrometer/runtime/MicrometerTimedInterceptorTest.java#L43 for example

Comment (mariofusco) [reply agentic/deployment/src/test/java/io/quarkiverse/langchain4j/agentic/deployment/AgentPrometheusTest.java]: Done, please give it another look.

File: agentic/deployment/src/test/java/io/quarkiverse/langchain4j/agentic/deployment/AgentMeterRegistryTest.java [hunk 2]
```diff
@@ -0,0 +1,171 @@
...
+
+    @Test
+    void agentAndAiServiceTokenUsageMetricsHaveConsistentTagKeys() throws Exception {
+        agent.ask("test question");
+
+        assertThat(registry.find("gen_ai.client.token.usage").counters())
+                .as("Agent call should have produced token usage metrics")
+                .isNotEmpty();
+
+        io.vertx.core.Context dupCtx = VertxContext.createNewDuplicatedContext(vertx.getOrCreateContext());
```
Comment (geoand) [inline agentic/deployment/src/test/java/io/quarkiverse/langchain4j/agentic/deployment/AgentMeterRegistryTest.java]: Minor nitpick: I don't see why the full class name should be used

File: agentic/deployment/src/test/java/io/quarkiverse/langchain4j/agentic/deployment/AgentMetricsTest.java [hunk 3]
```diff
@@ -0,0 +1,132 @@
...
+                .collect(Collectors.toSet());
+
+        assertThat(distinctTagKeySets)
+                .as("All meters with the same name must have identical tag keys (Prometheus requirement)")
+                .hasSize(1);
+    }
+
+    private static void assertTagKeysPresentOnAll(Collection<? extends io.micrometer.core.instrument.Meter> meters,
+            String... expectedKeys) {
+        for (io.micrometer.core.instrument.Meter meter : meters) {
```
Comment (geoand) [inline agentic/deployment/src/test/java/io/quarkiverse/langchain4j/agentic/deployment/AgentMetricsTest.java]: Same comment about the class name

File: agentic/deployment/src/test/java/io/quarkiverse/langchain4j/agentic/deployment/AgentPrometheusTest.java (hunk 1 above)
Comment (geoand) [reply agentic/deployment/src/test/java/io/quarkiverse/langchain4j/agentic/deployment/AgentPrometheusTest.java]: Thanks!

File: agentic/deployment/src/test/java/io/quarkiverse/langchain4j/agentic/deployment/AgentMeterRegistryTest.java (hunk 2 above)
Comment (mariofusco) [reply agentic/deployment/src/test/java/io/quarkiverse/langchain4j/agentic/deployment/AgentMeterRegistryTest.java]: Fixed.

File: agentic/deployment/src/test/java/io/quarkiverse/langchain4j/agentic/deployment/AgentMetricsTest.java (hunk 3 above)
Comment (mariofusco) [reply agentic/deployment/src/test/java/io/quarkiverse/langchain4j/agentic/deployment/AgentMetricsTest.java]: Fixed.

**Review by geoand — APPROVED** [review]
Thanks!
