### PR TITLE
Handle hallucinated tool execution requests

### LINKED ISSUE #1232: [Question] Memory deleted at the end of the request
Hi,

I am currently experimenting with the quarkus langchain4j features and I was wondering why the memory is not working. So I decided to implement a RedisMemoryStore myself. Now it seems to be used but after each request all messages are deleted since quarkus seems to call the `deleteMessages` Method on my Implementation of ChatMemoryStore

```java
@Default
@ApplicationScoped
public class RedisMemoryStore implements ChatMemoryStore {

    private final ValueCommands<String, List<ChatMessage>> valueCommands;
    private final KeyCommands<String> keyCommands;

    public RedisMemoryStore(RedisDataSource redisDataSource) {
        this.valueCommands = redisDataSource.value(new TypeReference<List<ChatMessage>>(){});
        this.keyCommands = redisDataSource.key();
    }

    @Override
    public List<ChatMessage> getMessages(Object memoryId) {
        if(keyCommands.exists(memoryId.toString())){
            return valueCommands.get(memoryId.toString());
        }
        {
            return Collections.emptyList();
        }
    }

    @Override
    public void updateMessages(Object memoryId, List<ChatMessage> messages) {
        valueCommands.set(memoryId.toString(), messages);
    }

    @Override
    public void deleteMessages(Object memoryId) {
        keyCommands.del(memoryId.toString());
    }

}
```

Behavior:

1. all the RAG functionality is run
2. deleteMessages with the specified MemoryId is called
3. updateMessages is called for all the messages (systemmessage, query, retrival, tools...)
4. deleteMessages is called again resulting in the deletion of all messages in redis

Can someone explain this behavior?

### PR DESCRIPTION
**Pull request by JanHuege**
Not sure why I needed to add the quarkus-junit5 dependency for my test to run.

Added behavior to filter out hallucinated toolExecutionRequests.

Had to add some reflection to write a test with mocked client in OllamaChatLanguageModel. I am happy about suggestions.

Also I am not happy with the assertions in the test "doesNotCrashIfToolNotPresent". But I did not find out how to get the content of the messagebuilder from "chatResponseWithHalucinatedTool" to be present in the resultin ChatResponse. I think it has something todo with missing ToolExecutors but added breakpoints into the ToolExecutors present in the repo did not help since they didn't hit.

Fixes #1232 (hallucinated toolExecutionRequests)

### CODE REVIEW

File: model-providers/ollama/runtime/src/test/java/io/quarkiverse/langchain4j/ollama/OllamaChatLanguageModelTest.java [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+import org.junit.jupiter.api.Test;
+import org.mockito.Mockito;
+
+import dev.langchain4j.agent.tool.ToolSpecification;
+import dev.langchain4j.data.message.UserMessage;
+import dev.langchain4j.model.chat.request.ChatRequest;
+import io.quarkus.test.junit.QuarkusTest;
+
+@QuarkusTest
+class OllamaChatLanguageModelTest {
```
Comment (geoand) [inline model-providers/ollama/runtime/src/test/java/io/quarkiverse/langchain4j/ollama/OllamaChatLanguageModelTest.java:19]: Can you please move the test to the `deploment` module? That's where `@QuarkusTest` tests belong

File: model-providers/ollama/runtime/pom.xml [hunk 2]
```diff
@@ -47,6 +47,11 @@
             <version>${assertj.version}</version>
             <scope>test</scope>
         </dependency>
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarkus-junit5</artifactId>
+            <scope>test</scope>
+        </dependency>
```
Comment (geoand) [inline model-providers/ollama/runtime/pom.xml:54]: With the move of the test to the `deployment` module, this won't be needed

**Review by geoand — COMMENTED** [review]
Thanks a lot!

I'll have a closer look tomorrow, but for now I added a comment about the test

**Comment by geoand** [comment]
As for the tests, I would much rather prefer to have a tool test like the ones in the OpenAI module

**Comment by JanHuege** [comment]
I moved the tests and I've rewritten them to match the wiremock style of the others in ollama but I saw your latest remark after I was done. 

Are you talking about `ToolBoxTest` and others in `quarkus-langchain4j-openai-deployment` ?

I am not sure if I understand the setup of those.

**Comment by geoand** [comment]
> Are you talking about ToolBoxTest and others in quarkus-langchain4j-openai-deployment ?

Right. It's similar to the other Wiremock tests and the idea is to be able to track whether a tool has been called or not.

**Comment by JanHuege** [comment]
I have added a scenario test somewhat equal to the ones in the openai package. I had to add the called property as a static one since I was unable to use an AtomicInteger like in `ToolsApplicationScopedWithInterceptorTest.java` since injecting the Tool creates a second AppScoped Instance making it impossible to check if called is 1. So I helped myself with this somewhat hacky solution. If you got a nicer way of ensuring the call with something like a spy I'd appreciate it.

I kept the other ones since I feel like checking/asserting the filtering of the execution is somewhat neccessary to ensure that calls are filtered out. For me without the other testcases this would cause blindspots.

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by JanHuege** [comment]
Fixed the formatting 

> > 🌘 **_This workflow status is outdated as a new workflow run has been triggered._**
> 
> # Status for workflow `Build (on pull request)`
> This is the status report for running `Build (on pull request)` on commit [62bf751](https://github.com/quarkiverse/quarkus-langchain4j/commit/62bf751e35b151213d63f03d4045351ddb5e9ade).
> 
> ## Failing Jobs
> Status	Name	Step	Failures	Logs	Raw logs
> ✖	Quick Build	`Build with Maven`	[Failures](#user-content-test-failures-job-36217023102)	[Logs](https://github.com/quarkiverse/quarkus-langchain4j/actions/runs/12987161946/job/36217023102)	[Raw logs](https://github.com/quarkiverse/quarkus-langchain4j/commit/62bf751e35b151213d63f03d4045351ddb5e9ade/checks/36217023102/logs)
> ## Failures
> ### ⚙️ Quick Build [#](#user-content-test-failures-job-36217023102)
> ```diff
> - Failing: model-providers/ollama/deployment 
> ! Skipped: codestarts codestarts/chatbot codestarts/chatbot/deployment and 65 more
> ```
> 
> #### 📦 model-providers/ollama/deployment
> ✖ `` Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.24.1:validate (default) on project quarkus-langchain4j-ollama-deployment: File '/home/runner/work/quarkus-langchain4j/quarkus-langchain4j/model-providers/ollama/deployment/src/test/java/io/quarkiverse/langchain4j/ollama/deployment/OllamaChatLanguageModelToolTest.java' has not been previously formatted. Please format file (for example by invoking `mvn -f model-providers/ollama/deployment net.revelc.code.formatter:formatter-maven-plugin:2.24.1:format`) and commit before running validation! ``

**Comment by JanHuege** [comment]
fixed sorting of imports
