### PR TITLE
Fix Azure endpoint properties and baseUrl computation

### LINKED ISSUE #248: Clarify Azure properties
When invoking Azure OpenAI with pure LangChain4j, this is the code you need:

```java
AzureOpenAiChatModel model = AzureOpenAiChatModel.builder()
      .apiKey(AZURE_OPENAI_KEY)
      .endpoint(AZURE_OPENAI_ENDPOINT)
      .deploymentName(AZURE_OPENAI_DEPLOYMENT_NAME)
      .temperature(0.9)
      .build();
```

`apiKey`, `endpoint` and `deploymentName` are mandatory. If you look at the Azure Console, the Deployment Name is random name you can choose and then you deploy a model (`gpt-35-turbo`)

Screenshot 2024-01-26 at 14 46 23

At the moment, the extension had four mandatory properties instead of three:

```
quarkus.langchain4j.azure-openai.api-key=
quarkus.langchain4j.azure-openai.endpoint=
quarkus.langchain4j.azure-openai.deployment-id=
quarkus.langchain4j.azure-openai.resource-name=
```

Could we rename `deployment-id` with `deployment-name` so that it fits better with the LangChain4j API (`deploymentName`) and the Azure naming convention ? 

And what is `resource-name` (I thought it would be the model name, but it does not work) and why it is mandatory ?

cc @edeandrea @geoand

### PR DESCRIPTION
**Pull request by edeandrea**
Refactor Azure endpoint properties and how the baseUrl is computed.

See [this issue comment](https://github.com/quarkiverse/quarkus-langchain4j/issues/248#issuecomment-1912207740).

Fixes #248

### CODE REVIEW

**Comment by edeandrea** [comment]
@geoand / @agoncal please take a look

File: openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java [hunk 1]
```diff
@@ -85,18 +92,44 @@ public Supplier<?> embeddingModel(Langchain4jAzureOpenAiConfig runtimeConfig) {
...
-            public Object get() {
+            public EmbeddingModel get() {
                 return builder.build();
             }
         };
     }
 
-    private String getBaseUrl(Langchain4jAzureOpenAiConfig runtimeConfig) {
-        var baseUrl = runtimeConfig.baseUrl();
+    static String getEndpoint(Langchain4jAzureOpenAiConfig runtimeConfig) {
```
Comment (geoand) [inline openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java:101]: You know what I'm going to say: 

No lambdas in runtime code please

**Review by geoand — COMMENTED** [review]
Thanks!

I made a small comment

File: openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java (hunk 1 above)
Comment (edeandrea) [reply openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java:101]: I'll make the changes on Monday, but.....

One of these days I'd like to have you really explain to me the significance of lambdas in runtime code. Not that I don't believe you, but because I'd like to understand.

The code as written is so much cleaner and easier to read. `Optional.isPresent()` followed by `get()` is a total anti-pattern as well.

Comment (geoand) [reply openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java:101]: We've had this discussion before 🙂

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by edeandrea** [comment]
@geoand I just pushed new commits for the re-naming of `deployment-id` to `deployment-name` as well as remove the lambdas per [your comment](https://github.com/quarkiverse/quarkus-langchain4j/pull/249#discussion_r1468488729).

**Comment by geoand** [comment]
Indeed.

I'll add some of the Quarkus labels here too

**Comment by edeandrea** [comment]
I'm not sure why the JDK 17 build is failing. The failure is in some other module that I didn't touch.

**Comment by geoand** [comment]
Yeah, it's a known bug that makes GraalVM hang
